const constants = {
  FETCH_USER: "FETCH_USER",
  FETCH_WALLET: "FETCH_WALLET",
  FETCH_ACCOUNTS: "FETCH_ACCOUNTS",
  ADD_FUND_AMOUNT: "ADD_FUND_AMOUNT",
  ADD_FUND_CURRENCY: "ADD_FUND_CURRENCY",
  FUND_SUCCESS: "FUND_SUCCESS",
  FUND_FAILURE: "FUND_FAILURE",
  ADD_BANK: "ADD_BANK",
  REMOVE_BANK: "REMOVE_BANK",
  BANK_VERIFY_SUCCESS: "BANK_VERIFY_SUCCESS",
  BANK_VERIFY_FAILURE: "BANK_VERIFY_FAILURE",
  ID_VERIFY: "ID_VERIFY",
  ID_VERIFY_SUCCESS: "ID_VERIFY_SUCCESS",
  ID_VERIFY_FAILURE: "ID_VERIFY_FAILURE",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants
