const constants = {
  FETCH_USER: 'FETCH_USER',
  CREATE_NEW_USER: 'CREATE_NEW_USER',
  PHONE_VERIFY_SUCCESS: 'PHONE_VERIFY_SUCCESS',
  PHONE_VERIFY_FAIL: 'PHONE_VERIFY_FAIL',
  ADD_USER_DETAILS: 'ADD_USER_DETAILS',
  USER_ID_VERIFY: 'USER_ID_VERIFY',
  ID_VERIFY_SUCCESS: 'ID_VERIFY_SUCCESS',
  ID_VERIFY_FAILURE: 'ID_VERIFY_FAILURE',
  ADD_FUND_AMOUNT: 'ADD_FUND_AMOUNT',
  ADD_FUND_CURRENCY: 'ADD_FUND_CURRENCY',
  FUND_SUCCESS: 'FUND_SUCCESS',
  FUND_FAILURE: 'FUND_FAILURE',
  FETCH_WALLET: 'FETCH_WALLET',
  FETCH_ACCOUNTS: 'FETCH_ACCOUNTS',
  ADD_BANK: 'ADD_BANK',
  REMOVE_BANK: 'REMOVE_BANK',
  BANK_VERIFY_SUCCESS: 'BANK_VERIFY_SUCCESS',
  BANK_VERIFY_FAILURE: 'BANK_VERIFY_FAILURE',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
}

export default constants
